title: Zichang Xiang # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Zichang Xiang 
  <br><br>
  PhD Candidate in Statistical Science @ SMU | MS in Statistics @ NCSU
  <br><br>
  <a href="https://www.linkedin.com/in/zichangxiang/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Zichang23">View My Github Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
